# Generated by Django 4.1.7 on 2023-02-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=20, verbose_name='Produto')),
                ('item_description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('item_quantity', models.IntegerField(verbose_name='Quantidade')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Total')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('itens', models.ManyToManyField(to='core.order')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Usuario'),
        ),
    ]
