# Generated by Django 4.1.7 on 2023-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
    ]
